CUDA_VISIBLE_DEVICES=5 python scripts/main_tf_example.py  --ckpt /mnt/nfs-mnj-home-43/i24_ziliu/i24_ziliu/Foreground2Background/Reference_Code/TF-ICON/ckpt/v2-1_512-ema-pruned.ckpt      \
                                --root ./inputs/cross_domain      \
                                --domain 'cross'                  \
                                --dpm_steps 20                    \
                                --dpm_order 2                     \
                                --scale 5                         \
                                --tau_a 0.4                       \
                                --tau_b 0.8                       \
                                --outdir ./outputs                \
                                --gpu cuda:0                      \
                                --seed 3407                         